spring:
  application:
    name: Quiz
#  datasource:
#    url: ${DATABASE_URL:jdbc:postgresql://167.88.33.180:3090/postgresql_16}
#    username: ${DATABASE_USERBAME:postgres}
#    password: ${DATABASE_PASSWORD:cc48628968f7a2f7440e}
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver

security-configurations:
  jwt:
    secret: ${JWT_SECRET:/g0lkq/qOxZ3tXv4CVOkYSJVoRc3WVpTHDRTgM8QDaKS/5kihyUg2JaBrDyODHal}
    expiration: 720000000000

access:
  code:
    length: 7